from __future__ import annotations

import html
from pathlib import Path
from typing import Any


SEVERITIES = ["info", "low", "medium", "high", "critical"]
CONFIDENCES = ["low", "medium", "high"]

SAFETY_DISCLAIMER = (
    "This report was generated by AI Security Analyst for authorized security assessment only. "
    "The current pipeline performs passive/dummy analysis and does not execute exploitation, "
    "brute force, denial-of-service, credential theft, or unauthorized access. All findings are "
    "potential findings and require manual validation before being treated as confirmed vulnerabilities."
)


def escape_html(value: object) -> str:
    return html.escape(str(value if value is not None else ""), quote=True)


def _item_value(item: object, key: str, default: object = "") -> object:
    if isinstance(item, dict):
        return item.get(key, default)
    return getattr(item, key, default)


def _as_list(value: object) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, (tuple, set)):
        return list(value)
    return [value]


def count_by_key(items: list[dict] | list[object], key: str, expected_values: list[str]) -> dict[str, int]:
    counts = {value: 0 for value in expected_values}
    for item in items or []:
        value = str(_item_value(item, key, "") or "").strip().lower()
        if value in counts:
            counts[value] += 1
    return counts


def summarize_report(scan_result: dict[str, Any]) -> dict[str, Any]:
    audit_log = scan_result.get("audit_log") if isinstance(scan_result.get("audit_log"), dict) else {}
    findings = _as_list(scan_result.get("findings"))
    return {
        "assets_count": len(_as_list(scan_result.get("assets"))),
        "endpoints_count": len(_as_list(scan_result.get("endpoints"))),
        "findings_count": len(findings),
        "commands_executed_count": len(_as_list(audit_log.get("commands_executed"))),
        "modules_enabled_count": len(_as_list(audit_log.get("modules_enabled"))),
        "status": str(scan_result.get("status", "")),
        "severity_summary": count_by_key(findings, "severity", SEVERITIES),
        "confidence_summary": count_by_key(findings, "confidence", CONFIDENCES),
    }


def _render_table(headers: list[str], rows: list[list[object]], class_name: str = "") -> str:
    class_attr = f' class="{escape_html(class_name)}"' if class_name else ""
    head = "".join(f"<th>{escape_html(header)}</th>" for header in headers)
    body_rows = []
    for row in rows:
        cells = "".join(f"<td>{escape_html(cell)}</td>" for cell in row)
        body_rows.append(f"<tr>{cells}</tr>")
    body = "\n".join(body_rows)
    return f"<table{class_attr}><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def render_list_items(items: list[object], empty_message: str) -> str:
    values = _as_list(items)
    if not values:
        return f"<p>{escape_html(empty_message)}</p>"
    rendered = []
    for item in values:
        if isinstance(item, dict):
            value = item.get("url") or item.get("value") or item.get("path") or item
        else:
            value = item
        rendered.append(f"<li>{escape_html(value)}</li>")
    return "<ul>" + "".join(rendered) + "</ul>"


def render_findings_table(findings: list[object]) -> str:
    values = _as_list(findings)
    if not values:
        return "<p>No findings recorded.</p>"
    rows = []
    for finding in values:
        rows.append(
            [
                _item_value(finding, "title"),
                _item_value(finding, "severity"),
                _item_value(finding, "confidence"),
                _item_value(finding, "asset"),
                _item_value(finding, "endpoint"),
                _item_value(finding, "module"),
                _item_value(finding, "finding_type"),
                _item_value(finding, "evidence"),
                _item_value(finding, "recommendation"),
                _item_value(finding, "source"),
                _item_value(finding, "is_potential"),
            ]
        )
    return _render_table(
        [
            "Title",
            "Severity",
            "Confidence",
            "Asset",
            "Endpoint",
            "Module",
            "Finding Type",
            "Evidence",
            "Recommendation",
            "Source",
            "Potential",
        ],
        rows,
        "findings-table",
    )


def _render_count_table(counts: dict[str, int], label: str) -> str:
    rows = [[key, value] for key, value in counts.items()]
    return _render_table([label, "Count"], rows)


def _render_audit_log(audit_log: dict[str, Any]) -> str:
    modules = _as_list(audit_log.get("modules_enabled"))
    commands = _as_list(audit_log.get("commands_executed"))
    errors = _as_list(audit_log.get("errors"))
    modules_html = render_list_items(modules, "No modules enabled.")
    commands_html = "<p>No external commands executed.</p>" if not commands else render_list_items(commands, "No external commands executed.")
    errors_html = render_list_items(errors, "No errors recorded.")
    return f"""
    <div class="audit-log">
        <p><strong>Modules enabled</strong></p>
        {modules_html}
        <p><strong>Commands executed</strong></p>
        {commands_html}
        <p><strong>Errors</strong></p>
        {errors_html}
        <p><strong>Findings generated:</strong> {escape_html(audit_log.get("findings_generated", 0))}</p>
    </div>
    """


def _css() -> str:
    return """
    <style>
        body { margin: 0; font-family: Arial, sans-serif; color: #172033; background: #f5f7fb; }
        .report-container { max-width: 1120px; margin: 0 auto; padding: 32px; background: #fff; }
        .report-header { border-bottom: 2px solid #d8deea; margin-bottom: 24px; padding-bottom: 16px; }
        .report-header h1 { margin: 0 0 6px; font-size: 28px; }
        .report-header h2 { margin: 0; font-size: 18px; color: #46546f; font-weight: 500; }
        .summary-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 12px; margin: 16px 0; }
        .summary-card { border: 1px solid #d8deea; border-radius: 6px; padding: 12px; background: #f9fbff; }
        .summary-card strong { display: block; font-size: 20px; margin-bottom: 4px; }
        .section { margin: 28px 0; }
        .section h3 { margin-bottom: 10px; border-bottom: 1px solid #e6eaf2; padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }
        th, td { border: 1px solid #d8deea; padding: 8px; text-align: left; vertical-align: top; }
        th { background: #eef3fb; }
        .findings-table td { word-break: break-word; }
        .severity-info { color: #315c83; }
        .severity-low { color: #397237; }
        .severity-medium { color: #946200; }
        .severity-high { color: #a44200; }
        .severity-critical { color: #9b111e; font-weight: bold; }
        .disclaimer { border: 1px solid #f0d28a; background: #fff8e5; padding: 14px; border-radius: 6px; }
        .audit-log { border: 1px solid #d8deea; background: #fbfcff; padding: 12px; border-radius: 6px; }
    </style>
    """


def generate_html_report(scan_result: dict[str, Any]) -> str:
    result = scan_result if isinstance(scan_result, dict) else {}
    summary = summarize_report(result)
    audit_log = result.get("audit_log") if isinstance(result.get("audit_log"), dict) else {}
    allowed_scope = result.get("allowed_scope") if isinstance(result.get("allowed_scope"), dict) else {}
    domains = _as_list(allowed_scope.get("domains") or allowed_scope.get("allowed_domains"))
    ips = _as_list(allowed_scope.get("ips") or allowed_scope.get("allowed_ips"))

    return f"""<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>AI Security Analyst - Security Reconnaissance Report</title>
    {_css()}
</head>
<body>
<main class="report-container">
    <header class="report-header">
        <h1>AI Security Analyst</h1>
        <h2>Security Reconnaissance Report</h2>
        <table>
            <tbody>
                <tr><th>Scan ID</th><td>{escape_html(result.get("scan_id", ""))}</td></tr>
                <tr><th>Target</th><td>{escape_html(result.get("target", ""))}</td></tr>
                <tr><th>Normalized target</th><td>{escape_html(result.get("normalized_target", ""))}</td></tr>
                <tr><th>Scan mode</th><td>{escape_html(result.get("scan_mode", ""))}</td></tr>
                <tr><th>Status</th><td>{escape_html(result.get("status", ""))}</td></tr>
                <tr><th>Started at</th><td>{escape_html(result.get("started_at", ""))}</td></tr>
                <tr><th>Ended at</th><td>{escape_html(result.get("ended_at", ""))}</td></tr>
            </tbody>
        </table>
    </header>

    <section class="section">
        <h3>Authorized Scope</h3>
        <p>This report is valid only for the authorized scope listed below.</p>
        <p><strong>Allowed domains</strong></p>
        {render_list_items(domains, "No allowed domains recorded.")}
        <p><strong>Allowed IPs</strong></p>
        {render_list_items(ips, "No allowed IPs recorded.")}
    </section>

    <section class="section">
        <h3>Executive Summary</h3>
        <p>This report summarizes passive reconnaissance and potential security findings for the authorized target. All findings are potential and require manual validation.</p>
        <div class="summary-grid">
            <div class="summary-card"><strong>{escape_html(summary["assets_count"])}</strong>Assets</div>
            <div class="summary-card"><strong>{escape_html(summary["endpoints_count"])}</strong>Endpoints</div>
            <div class="summary-card"><strong>{escape_html(summary["findings_count"])}</strong>Potential Findings</div>
            <div class="summary-card"><strong>{escape_html(summary["commands_executed_count"])}</strong>Commands Executed</div>
            <div class="summary-card"><strong>{escape_html(summary["modules_enabled_count"])}</strong>Modules Enabled</div>
        </div>
        <p><strong>Status scan:</strong> {escape_html(summary["status"])}</p>
    </section>

    <section class="section">
        <h3>Attack Surface Summary</h3>
        {_render_table(["Metric", "Count"], [["Assets", summary["assets_count"]], ["Endpoints", summary["endpoints_count"]], ["Findings", summary["findings_count"]], ["Modules enabled", summary["modules_enabled_count"]], ["Commands executed", summary["commands_executed_count"]]])}
    </section>

    <section class="section">
        <h3>Assets</h3>
        {render_list_items(_as_list(result.get("assets")), "No assets recorded.")}
    </section>

    <section class="section">
        <h3>Endpoints</h3>
        {render_list_items(_as_list(result.get("endpoints")), "No endpoints recorded.")}
    </section>

    <section class="section">
        <h3>Findings</h3>
        {render_findings_table(_as_list(result.get("findings")))}
    </section>

    <section class="section">
        <h3>Severity Summary</h3>
        {_render_count_table(summary["severity_summary"], "Severity")}
    </section>

    <section class="section">
        <h3>Confidence Summary</h3>
        {_render_count_table(summary["confidence_summary"], "Confidence")}
    </section>

    <section class="section">
        <h3>Audit Log</h3>
        {_render_audit_log(audit_log)}
    </section>

    <section class="section disclaimer">
        <h3>Safety Disclaimer</h3>
        <p>{escape_html(SAFETY_DISCLAIMER)}</p>
    </section>
</main>
</body>
</html>
"""


def save_html_report(scan_result: dict[str, Any], output_path: str) -> str:
    path = Path(output_path)
    if path.suffix.lower() != ".html":
        path = path.with_suffix(".html")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(generate_html_report(scan_result), encoding="utf-8")
    return str(path)

